# Generated by Django 5.2.9 on 2025-12-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfilusuario',
            table='perfil_usuario_legacy',
        ),
        migrations.AlterModelTable(
            name='registro',
            table='registro_legacy',
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['rut'], name='clientes_rut_82759a_idx'), models.Index(fields=['nombre'], name='clientes_nombre_4aa028_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('VIEW', 'Ver'), ('CREATE', 'Crear'), ('EDIT', 'Editar'), ('DELETE', 'Eliminar'), ('AUDIT', 'Auditar'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('APPROVE', 'Aprobar')], max_length=20)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'indexes': [models.Index(fields=['codigo'], name='permisos_codigo_111d3c_idx')],
                'unique_together': {('codigo', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ReglasNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('INFO', 'Información')], max_length=20)),
                ('condicion', models.TextField()),
                ('entidad', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reglas de Negocio',
                'db_table': 'reglas_negocio',
                'indexes': [models.Index(fields=['codigo'], name='reglas_nego_codigo_7113d1_idx'), models.Index(fields=['entidad'], name='reglas_nego_entidad_769903_idx')],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CORREDOR', 'Corredor de inversión'), ('ANALISTA', 'Analista tributario'), ('AUDITOR', 'Auditor interno'), ('TI', 'Administrador TI')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'indexes': [models.Index(fields=['nombre'], name='roles_nombre_ec8c3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='src.roles')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SesionesActivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='src.usuarios')),
            ],
            options={
                'db_table': 'sesiones_activas',
            },
        ),
        migrations.CreateModel(
            name='ReportesGenerados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('AUDITORIA', 'Auditoría'), ('CALIFICACIONES', 'Calificaciones'), ('CARGA_MASIVA', 'Carga Masiva'), ('SEGURIDAD', 'Seguridad'), ('CUMPLIMIENTO', 'Cumplimiento')], max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('archivo_path', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/%d/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_periodo', models.DateField(blank=True, null=True)),
                ('fecha_fin_periodo', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='src.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reportes_generados',
            },
        ),
        migrations.CreateModel(
            name='LogsSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTH_FAILED', 'Fallo de autenticación'), ('UNAUTHORIZED_ACCESS', 'Acceso no autorizado'), ('SQL_INJECTION_ATTEMPT', 'Intento de SQL Injection'), ('XSS_ATTEMPT', 'Intento de XSS'), ('RATE_LIMIT', 'Límite de velocidad excedido'), ('SUSPICIOUS_ACTIVITY', 'Actividad sospechosa'), ('PRIVILEGE_ESCALATION', 'Intento de escalada de privilegios'), ('DATA_BREACH', 'Posible fuga de datos')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('descripcion', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('severidad', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRÍTICO', 'Crítico')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('investigado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Logs de Seguridad',
                'db_table': 'logs_seguridad',
            },
        ),
        migrations.CreateModel(
            name='CargasMasivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_path', models.FileField(upload_to='cargas_masivas/%Y/%m/%d/')),
                ('tipo_carga', models.CharField(max_length=50)),
                ('total_registros', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('COMPLETADO_CON_ERRORES', 'Completado con Errores'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('log_errores', models.JSONField(blank=True, default=dict)),
                ('resultado_resumen', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_masivas', to='src.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Cargas Masivas',
                'db_table': 'cargas_masivas',
            },
        ),
        migrations.CreateModel(
            name='CalificacionesTributarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6)),
                ('instrumento', models.CharField(max_length=50)),
                ('valor_calificacion', models.CharField(max_length=5)),
                ('monto_asociado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(choices=[('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('ERROR', 'Error'), ('PENDIENTE', 'Pendiente'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='src.clientes')),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_asignadas', to='src.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'calificaciones_tributarias',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('VIEW', 'Ver')], max_length=50)),
                ('entidad', models.CharField(max_length=50)),
                ('entidad_id', models.IntegerField(blank=True, null=True)),
                ('valor_anterior', models.JSONField(blank=True, default=dict)),
                ('valor_nuevo', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('FALLO', 'Fallo')], default='EXITO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to='src.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Auditoría',
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='RolPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='src.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='src.roles')),
            ],
            options={
                'db_table': 'rol_permisos',
                'indexes': [models.Index(fields=['rol', 'permiso'], name='rol_permiso_rol_id_88051b_idx')],
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['username'], name='usuarios_usernam_7abab6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['rut'], name='usuarios_rut_5379eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['rol'], name='usuarios_rol_id_040259_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionesactivas',
            index=models.Index(fields=['usuario', 'revoked'], name='sesiones_ac_usuario_715c27_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionesactivas',
            index=models.Index(fields=['fecha_expiracion'], name='sesiones_ac_fecha_e_7b6155_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesgenerados',
            index=models.Index(fields=['usuario', 'fecha_generacion'], name='reportes_ge_usuario_a20a87_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesgenerados',
            index=models.Index(fields=['tipo_reporte'], name='reportes_ge_tipo_re_ed7969_idx'),
        ),
        migrations.AddIndex(
            model_name='logsseguridad',
            index=models.Index(fields=['tipo', 'fecha'], name='logs_seguri_tipo_1477de_idx'),
        ),
        migrations.AddIndex(
            model_name='logsseguridad',
            index=models.Index(fields=['severidad', 'investigado'], name='logs_seguri_severid_868ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='logsseguridad',
            index=models.Index(fields=['ip_address', 'fecha'], name='logs_seguri_ip_addr_614680_idx'),
        ),
        migrations.AddIndex(
            model_name='cargasmasivas',
            index=models.Index(fields=['usuario', 'fecha'], name='cargas_masi_usuario_adabd4_idx'),
        ),
        migrations.AddIndex(
            model_name='cargasmasivas',
            index=models.Index(fields=['estado'], name='cargas_masi_estado_e7d790_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionestributarias',
            index=models.Index(fields=['cliente', 'periodo'], name='calificacio_cliente_6ff2db_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionestributarias',
            index=models.Index(fields=['estado'], name='calificacio_estado_4f793f_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionestributarias',
            index=models.Index(fields=['analista'], name='calificacio_analist_660bd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionestributarias',
            unique_together={('cliente', 'periodo', 'instrumento')},
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario', 'fecha'], name='auditoria_usuario_c2e4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_9c3bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion', 'fecha'], name='auditoria_accion_1059e7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['fecha'], name='auditoria_fecha_b71d64_idx'),
        ),
    ]
