# Generated by Django 5.2.9 on 2025-12-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_perfilusuario_table_alter_registro_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='Auditoria'),
        migrations.DeleteModel(name='CalificacionesTributarias'),
        migrations.DeleteModel(name='Clientes'),
        migrations.DeleteModel(name='CargasMasivas'),
        migrations.DeleteModel(name='LogsSeguridad'),
        migrations.DeleteModel(name='Permisos'),
        migrations.DeleteModel(name='ReportesGenerados'),
        migrations.DeleteModel(name='ReglasNegocio'),
        migrations.DeleteModel(name='RolPermisos'),
        migrations.DeleteModel(name='Roles'),
        migrations.DeleteModel(name='SesionesActivas'),
        migrations.DeleteModel(name='Usuarios'),
    ]
