# Generated by Django 5.2.9 on 2025-12-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_auditoria_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfilusuario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='registro',
            table=None,
        ),
    ]
