# Generated by Django 5.2.6 on 2025-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auditoria_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='detalle',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='rol',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
