# Generated by Django 5.2.6 on 2025-12-14 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_auditoria_accion_alter_reglanegocio_accion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReglaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('condicion', models.TextField()),
                ('accion', models.TextField()),
                ('version', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_snapshot', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, help_text='Razón del cambio')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_reglas', to=settings.AUTH_USER_MODEL)),
                ('regla_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_versiones', to='src.reglanegocio')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
