# Generated by Django 5.2.6 on 2025-12-14 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_perfilusuario_pais_verificacionemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Feedback'},
        ),
        migrations.CreateModel(
            name='CasoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caso', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('PROBLEMA', 'Problema'), ('MOLESTIA', 'Molestia'), ('SUGERENCIA', 'Sugerencia')], default='CONSULTA', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRÍTICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('email_contacto_enviado', models.BooleanField(default=False)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_respondidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_soporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', '-fecha_creacion'], name='src_casosop_estado_5fbfb9_idx'), models.Index(fields=['id_caso'], name='src_casosop_id_caso_2e81b9_idx')],
            },
        ),
    ]
