# Generated by Django 5.2.6 on 2025-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_alter_feedback_options_casosoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='solicitar_auditoria',
            field=models.BooleanField(default=False),
        ),
    ]
