"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent 

# Cargar variables de .env
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ----------------------------------------------------
# APPS
# ----------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "rest_framework_simplejwt",
    "django.contrib.staticfiles",

    # Apps externas
    "rest_framework",
    "corsheaders",

    # TU APP (SOLO UNA VEZ)
    "src.apps.SrcConfig",
]


# ----------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django.urls'

# ----------------------------------------------------
# TEMPLATES
# ----------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django.wsgi.application'

# ----------------------------------------------------
# DATABASE
# ----------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        # Prefer explicit DB_USER to avoid colliding with OS-level USER env on Windows
        'USER': os.getenv('DB_USER', os.getenv('USER')),
        'PASSWORD': os.getenv('PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# --- DEBUG: print DB params (temporary, remove after diagnosis) ---
try:
    _db_debug = {k: os.getenv(k) for k in ('DB_NAME','DB_USER','USER','PASSWORD','DB_HOST','DB_PORT')}
    # print reprs so bytes/encodings are visible in logs
    print('DEBUG DB ENV VARS:')
    for k, v in _db_debug.items():
        print(f"  {k}: {repr(v)}")
        if v is not None:
            try:
                print('    utf8 bytes:', list(v.encode('utf-8'))[:120])
            except Exception as _e:
                print('    encode error:', _e)
except Exception:
    pass

# ----------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------------------------------------
# STATIC FILES
# ----------------------------------------------------
STATIC_URL = 'static/'

# ----------------------------------------------------
# MEDIA FILES (Certificados)
# ----------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------
# CORS (React)
# ----------------------------------------------------
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:5174').split(',')

# ----------------------------------------------------
# Django REST Framework + SIMPLE JWT
# ----------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# ----------------------------------------------------
# SIMPLE JWT CONFIG
# ----------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # Acceso corto para seguridad
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),     # Refresh válido 7 días
    "ROTATE_REFRESH_TOKENS": True,                   # Rotar token en cada refresh
    "BLACKLIST_AFTER_ROTATION": True,                # Blacklist del token viejo
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.getenv('SECRET_KEY'),
}

# ----------------------------------------------------
# MONGODB CONFIG (para Calificaciones)
# ----------------------------------------------------
MONGODB_CONFIG = {
    'host': os.getenv('MONGODB_HOST', 'localhost'),
    'port': int(os.getenv('MONGODB_PORT', 27017)),
    'db_name': os.getenv('MONGODB_DB', 'nuam_calificaciones'),
    'username': os.getenv('MONGODB_USER', ''),
    'password': os.getenv('MONGODB_PASSWORD', ''),
    'auth_source': os.getenv('MONGODB_AUTH_SOURCE', 'admin'),
    'auth_mechanism': os.getenv('MONGODB_AUTH_MECHANISM', 'SCRAM-SHA-256'),
    'use_tls': os.getenv('MONGODB_TLS', 'False') == 'True',
    'tls_allow_invalid': os.getenv('MONGODB_TLS_ALLOW_INVALID', 'False') == 'True',
    'tls_ca_file': os.getenv('MONGODB_TLS_CA_FILE', ''),
    'kms_local_key': os.getenv('MONGODB_KMS_LOCAL_KEY', ''),
    'uri': os.getenv('MONGODB_URI', ''),
}
# ----------------------------------------------------
# EMAIL CONFIGURATION
# ----------------------------------------------------
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@ev3pi.com')

# URL del frontend para enlaces de verificación
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')